### ISSUE TITLE
Virtual Garage Scroll

### ISSUE THREAD

**Issue by Gr8z** [Bjanski/ExAd#40]
When the virtual garage has 5 or more vehicles, the stored tab does not appear to have a scroll bar. You can still use your keyboard to go down the list but it will not be visible. Using Scroll wheel will not work as well.

**Comment by Bjanski** [comment]
Thx for the feedback @Gr8z, I'll look into it.

**Comment by Gr8z** [comment]
Thank You @Bjanski

**Comment by Bjanski** [comment]
@Gr8z Since I'm not pushing the update now, you can fix it by changing "RscListBox" to "RscExileItemListBox" in file "XM8_apps\apps\XM8_VG\scripts\XM8_VG_mainVGSlide_onLoad.sqf" on line 70. 
From
`_ctrl = _display ctrlCreate ["RscListBox",_idc,_parent];`
To
`_ctrl = _display ctrlCreate ["RscExileItemListBox",_idc,_parent];`

This will use the RscExileItemListBox instead which has the scrollbar already built in. 
Will try to find a better fix for it but since I can't use mission defined controllers I have to use the mod defined or built in ones and for some reason ArmA's predefined doesn't have the scrollbar built in.

**Comment by Gr8z** [comment]
I have used `RscListBox` before in other XM8 apps. and they seem to perform fine. Also Forgot to mention, when you scroll wheel. Every single dialog in the app shifts up and down.

**Comment by Gr8z** [comment]
The Temp fix does not fix the scrolling issue.

**Comment by Bjanski** [comment]
@Gr8z I'm aware of that but haven't had any time to look into the code yet. 

Do you encounter this for all Improved XM8 Apps or is it only the Virtual Garage?

**Comment by Gr8z** [comment]
`Do you encounter this for all Improved XM8 Apps or is it only the Virtual Garage?`

Only the Virtual Garage has this problem.

**Comment by max-xface** [comment]
I made a change and got it here http://image.prntscr.com/image/008944bec74544c2966880e937b3c881.png

**Comment by Gr8z** [comment]
this is fully fixed after f222940
