### ISSUE TITLE
Function to call a Function?

### ISSUE THREAD

**Issue by MezoPlays** [Bjanski/ExAd#52]
Why do you have a [function ](https://github.com/Bjanski/ExAd/blob/master/mpmissions/Exile.Altis/ExAdClient/Core/Functions/Utils/fn_call.sqf)to call a function?

**Comment by Bjanski** [comment]
@MezoPlays  I used it in my AdminEvents to create functions which where hidden for the clients. The EXO community didn't want peolpe to steal all the code so we put all the code on the server and executed it from there and also since Exile overwrites BIS_fnc_call I was forced to create my own ;)

Might use it in the future again so I will leave it there for a while.

**Comment by MezoPlays** [comment]
Oh, git doesn't tell others when the "dev" replies apparently.

This is not really invalid, there's plenty of ways to do what you want to do without having a function to call a function :+1:

**Comment by Bjanski** [comment]
@MezoPlays  I'll remove the function since its a security risk.
